FROM python:3.10-slim

WORKDIR /app
COPY . /app

RUN python3.10 -m pip install --upgrade pip
RUN python3.10 -m pip install --no-cache-dir -r requirements.txt
RUN pip install pytest

CMD ["pytest", "tests_git_action/"]
