FROM public.ecr.aws/lambda/python:3.10

WORKDIR /app

# Copy requirements first
COPY requirements.txt .

RUN python -m pip install --upgrade pip \
    && pip install --no-cache-dir -r requirements.txt \
    && pip install pytest

# Copy code
COPY . .

ENV PYTHONPATH=/app

CMD ["pytest", "test_git_action/"]
