name: Build Docker & Run Tests

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Docker image for test
      run: docker build --no-cache -t Updated_app -f Dockerfile.test .

    - name: Run tests inside Docker
      run: |
        docker run --rm -w /app -e PYTHONPATH=/app Updated_app pytest test_git_action/
